export const recipeActions = {
  GET_ALL_RECIPES: 'GET_ALL_RECIPES',
  GET_USER_RECIPES: 'GET_USER_RECIPES',
  SET_ALL_RECIPES: 'SET_ALL_RECIPES',
  SET_FAVOURITE_RECIPES: 'SET_FAVOURITE_RECIPES',
  ADD_RECIPE: 'ADD_RECIPE'
};
